name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        git submodule update --init
        pip install -r lbm/requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --noconsole --onefile main.py

    - name: Run Inno Setup
      run: |
        iscc "installer_script.iss"

    - name: Upload Inno Setup Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lbm-setup
        path: output_directory
